version: '3.5'
services:
    logstash:
        image: logstash:7.17.9
        environment:
          # Так как сейчас вы хотите запустить logstash без Elasticsearch, необходимо отключить встроенный мониторинг, отправляющий данные в ES
          XPACK_MONITORING_ENABLED: "false"
          ES_HOST: "elasticsearch:9200"
        ports:
          - "5044:5044/udp"
        volumes:
          # Монтируем файл с конфигурацией logstash
          - ./logstash/logstash.conf:/config/logstash.conf:ro
        # Запускаем с указанием конфигурационного файла
        command: logstash -f /config/logstash.conf
        depends_on:
          - elasticsearch

    elasticsearch:
      image: elasticsearch:7.17.9
      environment:
        - xpack.security.enabled=false
        - "discovery.type=single-node"
      expose:
        - 9200

    kibana:
      container_name: kb-container
      image: kibana:7.17.9
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601