version: '3.5'

services:
  clickhouse:
    image: yandex/clickhouse-server:21.3-alpine
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G

  vertica:
    image: jbfavre/vertica:latest
    container_name: vertica
    hostname: vertica
    restart: always
    ports:
      - "5433:5433"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G