version: '3'
services:
  postgres:
    image: postgres:14.0
    container_name: postgres_cont
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    volumes:
    - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432


  airflow:
    build: .
    image: resdev-airflow:latest
    container_name: airflow_cont
    env_file:
      - .env
    restart: always
    command: webserver
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./airflow-data/dags:/opt/airflow/dags
      - ./airflow-data/plugins:/opt/airflow/plugins
      - logs-volume:/opt/airflow/logs

  airflow-scheduler:
    build: .
    image: resdev-airflow:latest
    container_name: airflow_scheduler_cont
    env_file:
      - .env
    restart: always
    command: scheduler
    depends_on:
      - postgres
    volumes:
      - ./airflow-data/dags:/opt/airflow/dags
      - ./airflow-data/plugins:/opt/airflow/plugins
      - logs-volume:/opt/airflow/logs


  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper


  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./data/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper



  ## Router
  router01:
    image: mongo:6.0.1
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_router01_db:/data/db
      - ./mongo/mongodb_cluster_router01_config:/data/configdb
  router02:
    image: mongo:6.0.1
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_router02_db:/data/db
      - ./mongo/mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - router01

## Config Servers
  configsvr01:
    image: mongo:6.0.1
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_configsvr01_db:/data/db
      - ./mongo/mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - shard01-a
      - shard02-a
      - shard03-a
  configsvr02:
    image: mongo:6.0.1
    container_name: mongo-config-02
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_configsvr02_db:/data/db
      - ./mongo/mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27120:27017
    restart: always
    links:
      - configsvr01
  configsvr03:
    image: mongo:6.0.1
    container_name: mongo-config-03
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_configsvr03_db:/data/db
      - ./mongo/mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27121:27017
    restart: always
    links:
      - configsvr02

## Shards
  ## Shards 01

  shard01-a:
    image: mongo:6.0.1
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard01_a_db:/data/db
      - ./mongo/mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo:6.0.1
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard01_b_db:/data/db
      - ./mongo/mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always
  shard01-c:
    image: mongo:6.0.1
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard01_c_db:/data/db
      - ./mongo/mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always

  ## Shards 02
  shard02-a:
    image: mongo:6.0.1
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard02_a_db:/data/db
      - ./mongo/mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo:6.0.1
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard02_b_db:/data/db
      - ./mongo/mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always

  shard02-c:
    image: mongo:6.0.1
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard02_c_db:/data/db
      - ./mongo/mongodb_cluster_shard02_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always


  ## Shards 03
  shard03-a:
    image: mongo:6.0.1
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard03_a_db:/data/db
      - ./mongo/mongodb_cluster_shard03_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - shard03-b
      - shard03-c

  shard03-b:
    image: mongo:6.0.1
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard03_b_db:/data/db
      - ./mongo/mongodb_cluster_shard03_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always


  shard03-c:
    image: mongo:6.0.1
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - ./mongo/mongodb_cluster_shard03_c_db:/data/db
      - ./mongo/mongodb_cluster_shard03_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always

volumes:
  database-data:
  logs-volume: